Update start-ec2.yml

diff --git a/.github/workflows/start-ec2.yml b/.github/workflows/start-ec2.yml
--- a/.github/workflows/start-ec2.yml
+++ b/.github/workflows/start-ec2.yml
@@ -33,6 +33,23 @@ jobs:
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_DEFAULT_REGION: "eu-west-2"
 
+    - name: Deploy
+      uses: appleboy/ssh-action@master
+      with:
+        host: 35.178.57.6
+        port: 22
+        username: ec2-user
+        key: ${{ secrets.DEV_SSH_KEY }}
+        script: |
+          # Try SSH connection
+          if ! ssh -o ConnectTimeout=10 -o BatchMode=yes -o StrictHostKeyChecking=no -i /dev/shm/ssh-private-key $USERNAME@$HOST -p $PORT "echo 'SSH connection successful'"; then
+            echo "Unable to SSH, starting EC2 instance..."
+            sleep 30
+          else
+            echo "SSH connection successful."
+          fi
+          sudo docker start $(sudo docker ps -a -q)
+
     - name: Skip Start if Already Running
       if: steps.ec2_status.outputs.instance_state == 'running'
       run: |
